[project]
name = "personal-finance"
version = "0.1.0"
description = "Personal finance data platform."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-api-python-client>=2.200.0",
    "google-auth-oauthlib>=1.4.1",
    "pdfplumber>=0.11.10",
    "psycopg[binary]>=3.2",
]

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
